---
title: "Fit GAM with mgcv"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gam_with_mgcv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
```


# Fit a GAM to CVP

Find a CVP curve

```{r}
sample_record2$vital$Intellivue$CVP %>% 
  dygraph_signal()
```

Find a less noisy period (e.g. 18:42:00 to 18:43:00)

```{r}
cvp <- sample_record2$vital$Intellivue$CVP %>% 
  filter(between(as_hms(time), as_hms("18:42:00"), as_hms("18:43:00"))) %>% 
  mutate(time_s = seconds_since_start(time))
```

```{r, fig.width = 10, fig.height = 4, out.width="100%"}
plot_signal(cvp)
```

Index cvp to respiratory and cardiac cycle

```{r}
cvp_indexed <- cvp %>% 
  gen_annotation_index(sample_record2$qrs$time, prefix = 'qrs') %>% 
  gen_annotation_index(sample_record2$vscapture$insp_start$time, prefix = 'insp')

head(cvp_indexed)
```

Fit GAM (with `bam()`: a faster version og `gam()`)

```{r}

cvp_gam <- bam(
        CVP ~ s(qrs_rel_index, bs = 'cc', k = 50) +
            s(insp_rel_index, bs = 'cc', k = 30) +
            ti(
                qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(20, 10)
            ) +
            s(time_s),
        method = 'REML',
        data = cvp_indexed,
        nthreads = 16 # Number of (virtual) cores
    )


```

Visualise GAM

```{r, fig.width = 10, fig.height = 7, out.width="100%"}
gratia::draw(cvp_gam)
```

```{r}
dygraph_gam(cvp_gam, resid = TRUE)
```

