---
title: "r shiny vis"
author: "Mads Varisbøl Clausen"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```


```{r}
data(airquality)

# Define UI for app that draws a histogram ----
ui <- fluidPage(
  
  # App title ----
  titlePanel("Ozone level!"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput(outputId = "distPlot")
      
    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  

  output$distPlot <- renderPlot({
    
    x    <- airquality$Ozone
    x    <- na.omit(x)
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "black",
         xlab = "Ozone level",
         main = "Histogram of Ozone level")
    
  })
  
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```


```{r}
# Import libraries
library(shiny)
library(shinythemes)
library(data.table)
library(RCurl)
library(randomForest)

# Read data
weather <- read.csv(text = getURL("https://raw.githubusercontent.com/dataprofessor/data/master/weather-weka.csv") )

# Build model
model <- randomForest(play ~ ., data = weather, ntree = 500, mtry = 4, importance = TRUE)

# Save model to RDS file
# saveRDS(model, "model.rds")

# Read in the RF model
#model <- readRDS("model.rds")

####################################
# User interface                   #
####################################

ui <- fluidPage(theme = shinytheme("united"),
  
  # Page header
  headerPanel('Play Golf?'),
  
  # Input values
  sidebarPanel(
    HTML("<h3>Input parameters</h3>"),
    
    selectInput("outlook", label = "Outlook:", 
                choices = list("Sunny" = "sunny", "Overcast" = "overcast", "Rainy" = "rainy"), 
                selected = "Rainy"),
    sliderInput("temperature", "Temperature:",
                min = 64, max = 86,
                value = 70),
    sliderInput("humidity", "Humidity:",
                min = 65, max = 96,
                value = 90),
    selectInput("windy", label = "Windy:", 
                choices = list("Yes" = "TRUE", "No" = "FALSE"), 
                selected = "TRUE"),
    
    actionButton("submitbutton", "Submit", class = "btn btn-primary")
  ),
  
  mainPanel(
    tags$label(h3('Status/Output')), # Status/Output Text Box
    verbatimTextOutput('contents'),
    tableOutput('tabledata') # Prediction results table
    
  )
)

####################################
# Server                           #
####################################

server <- function(input, output, session) {

  # Input Data
  datasetInput <- reactive({  
    
  # outlook,temperature,humidity,windy,play
  df <- data.frame(
    Name = c("outlook",
             "temperature",
             "humidity",
             "windy"),
    Value = as.character(c(input$outlook,
                           input$temperature,
                           input$humidity,
                           input$windy)),
    stringsAsFactors = FALSE)
  
  play <- "play"
  df <- rbind(df, play)
  input <- transpose(df)
  write.table(input,"input.csv", sep=",", quote = FALSE, row.names = FALSE, col.names = FALSE)
  
  test <- read.csv(paste("input", ".csv", sep=""), header = TRUE)
  
  test$outlook <- factor(test$outlook, levels = c("overcast", "rainy", "sunny"))
  
  
  Output <- data.frame(Prediction=predict(model,test), round(predict(model,test,type="prob"), 3))
  print(Output)
  
  })
  
  # Status/Output Text Box
  output$contents <- renderPrint({
    if (input$submitbutton>0) { 
      isolate("Calculation complete.") 
    } else {
      return("Server is ready for calculation.")
    }
  })
  
  # Prediction results table
  output$tabledata <- renderTable({
    if (input$submitbutton>0) { 
      isolate(datasetInput()) 
    } 
  })
  
}

####################################
# Create the shiny app             #
####################################
shinyApp(ui = ui, server = server)
```

# Our Shiny

```{r Denne virker}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
library(shiny)
library(shinythemes)


cvp <- sample_record2$vital$Intellivue$CVP %>% 
  filter(between(as_hms(time), as_hms("18:42:00"), as_hms("18:43:00"))) %>% 
  mutate(time_s = seconds_since_start(time))

cvp_indexed <- cvp %>% 
  gen_annotation_index(sample_record2$qrs$time, prefix = 'qrs') %>% 
  gen_annotation_index(sample_record2$vscapture$insp_start$time, prefix = 'insp')


ui <- fluidPage(theme = shinytheme("united"),
  
  # Page header
  headerPanel('Justering af parametre'),
  
  # Input values
  sidebarPanel(
    HTML("<h3>Input parameters</h3>"),

    sliderInput("qrs_rel_index", label = "qrs_rel_index - k",
                min = 0, max = 100,
                value = 50),
    sliderInput("insp_rel_index", label = "insp_rel_index - k",
                min = 0, max = 100,
                value = 30),
    selectInput("method", label = "Method:", 
                choices = list("REML" = "REML", "P-REML" = "P-REML", "ML" = "ML", "P-ML" = "P-ML", "fREML"="fREML"), 
                selected = "REML"),
    sliderInput("interaction_index1", label = "interaction_index1 - k",
                min = 0, max = 100,
                value = 20),
    sliderInput("interaction_index2", label = "interaction_index2 - k",
                min = 0, max = 100,
                value = 10),
    
  ),
      # Main panel for displaying outputs ----
    mainPanel(
      # Output: plots ----
      plotOutput(outputId = "samlet_plots")
    )

)

server <- function(input, output) {
  
  output$samlet_plots <- renderPlot({
    
    cvp_gam <- bam(
        CVP ~ s(qrs_rel_index, bs = 'cc', k = input$qrs_rel_index) +
            s(insp_rel_index, bs = 'cc', k = input$insp_rel_index) +
            ti(
                qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(input$interaction_index1, input$interaction_index2)
            ) +
            s(time_s),
        method = input$method,
        data = cvp_indexed,
        nthreads = 16 # Number of (virtual) cores
    )
    gratia::draw(cvp_gam)

  })
  
}
shinyApp(ui = ui, server = server)
```
```{r tester}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
library(shiny)
library(shinythemes)
library(shinyTime)


cvp <- sample_record2$vital$Intellivue$CVP %>% 
  filter(between(as_hms(time), as_hms("18:42:00"), as_hms("18:43:00"))) %>% 
  mutate(time_s = seconds_since_start(time))

cvp_indexed <- cvp %>% 
  gen_annotation_index(sample_record2$qrs$time, prefix = 'qrs') %>% 
  gen_annotation_index(sample_record2$vscapture$insp_start$time, prefix = 'insp')


ui <- fluidPage(theme = shinytheme("cerulean"),
  navbarPage("Shiny stuff",
             
  # Page header
  tabPanel("Justering af parametre",
  # Input values
  sidebarPanel(
    h3("Inputs"),
    sliderInput("qrs_rel_index", label = "qrs_rel_index - k",
                min = 0, max = 100,
                value = 50),
    sliderInput("insp_rel_index", label = "insp_rel_index - k",
                min = 0, max = 100,
                value = 30),
    selectInput("method", label = "Method:", 
                choices = list("REML" = "REML", "P-REML" = "P-REML", "ML" = "ML", 
                               "P-ML" = "P-ML",  "fREML"="fREML"), 
                selected = "REML"),
    sliderInput("interaction_index1", label = "interaction_index1 - k",
                min = 0, max = 100,
                value = 20),
    sliderInput("interaction_index2", label = "interaction_index2 - k",
                min = 0, max = 100,
                value = 10),
  
  # Set to custom time 
  timeInput("time_start", "Start", value = strptime("18:42:00", "%T")),
  
  timeInput("time_slut", "Slut", value = strptime("18:43:00", "%T")),
  
  ),
      # Main panel for displaying outputs ----
    mainPanel(
      # Output: plots ----
      plotOutput(outputId = "samlet_plots")
    )
  ),#tabpanel 1 slut
  
  tabPanel("Blomster og Bins bby", 
           sidebarPanel(
                h3("Blomster"),
    sliderInput("Bins_antal", label = "Bins baby",
                min = 1, max = 100,
                value = 50),
           ),
    mainPanel(
      # Output: plots ----
      plotOutput(outputId = "bin_plot")
      )
    ),
  
  tabPanel("Info", "Lavet af en sej studiegruppe")

  )#navbarpage 
)

server <- function(input, output) {
  
  output$samlet_plots <- renderPlot({
    
    cvp_gam <- bam(
        CVP ~ s(qrs_rel_index, bs = 'cc', k = input$qrs_rel_index) +
            s(insp_rel_index, bs = 'cc', k = input$insp_rel_index) +
            ti(
                qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(input$interaction_index1, input$interaction_index2)
            ) +
            s(time_s),
        method = input$method,
        #rho = 0.95,
        data = cvp_indexed,
        nthreads = 16 # Number of (virtual) cores
    )
    gratia::draw(cvp_gam)
  })# slutter renderPlot her
  
  output$bin_plot <- renderPlot({
    x <- iris$Sepal.Length
    x <- na.omit(x)
    bins = seq(min(x),max(x), length.out = input$Bins_antal +1)
    hist(x,breaks = bins)
  })
  
}
shinyApp(ui = ui, server = server)
# https://shiny.rstudio.com/articles/layout-guide.html
# https://www.youtube.com/watch?v=PHdIivFAq7Q
```


```{r}
dygraph_signal(sample_record2$vital$Intellivue$CVP) %>% dygraph_events(sample_record2$vent_event_labels)

predict(cvp_gam, terms = "s(insp_rel_index)") %>% plot
predict(cvp_gam, terms = "s(insp_rel_index)") %>% plot(type = "l")
```

