---
title: "Få RDS ind som plots"
author: "Mads Varisbøl Clausen"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls()) # clearing workspace
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
library(shiny)
library(shinythemes)
library(shinyTime)
library(data.table)
library(readr)
library(dygraphs)
library(dplyr)
library(cowplot)
```



```{r}
filepath <- "../GAM_RDS/pt07CLOSED.rds"
full_dataload <- readRDS(filepath, refhook = NULL)
```


```{r}
gratia::draw(full_dataload)
```



```{r}
paste("pt07", "CLOSED.rds", sep = "")
```





```{r loading data}
# path to folder containing patient files
 patient_file <- "../Datasets/thoracotomy_waveforms/"
```


```{r creating functions}
add_time <- function(data, ms_between_obs = 8, time_origin = "2021-09-03") {
  #' adds a column containing time with increments of ms_between_obs
  #' data:             a dataframe like structure
  #' ms_between_obs:   the amount of milliseconds between each cycle
  df <- tibble(data)
  df$time_ms <- seq(0, nrow(df)*ms_between_obs-ms_between_obs, ms_between_obs)
  df$time_s <- df$time_ms / 1000
  return(df)
}

create_patient_closed <- function(filepath) {
  #' creates a dataframe containing cvp and time in ms and s for open chest
  #' filepath:        the path of the patient file
  dataload <- readRDS(filepath, refhook = NULL)
  patient <- data.frame(cvp = dataload$closed_chest$CVP) # extract cvp numbers from data
  patient <- add_time(patient)
  return(patient)
}

create_patient_open <- function(filepath) {
  #' creates a dataframe containing cvp and time in ms and s for open chest
  #' filepath:        the path of the patient file
  dataload <- readRDS(filepath, refhook = NULL)
  patient <- data.frame(cvp = dataload$open_chest$CVP) # extract cvp numbers from data
  patient <- add_time(patient)
  return(patient)
}

all_in_one_patient <- function(filepath = patient_file, period = 'closed', slice_start = 130, slice_end = 190){
  #' Creates a dataframe containing all the good stuff for either the closed or open period
  full_dataload <- readRDS(filepath, refhook = NULL)
  if(period == 'closed'){
    pt3_closed <- create_patient_closed(filepath)
    qrs_ms_closed <- full_dataload$closed_chest$QRSmarker_ms
    pt3_closed <- na.omit(gen_annotation_index(pt3_closed, qrs_ms_closed, 'time_ms', 'qrs')) 
    pt3_closed <- na.omit(gen_annotation_index(pt3_closed, seq(0, nrow(pt3_closed)*8, 5000), 'time_ms', 'insp'))
    pt3_closed_sliced <- pt3_closed[pt3_closed$time_s > slice_start & pt3_closed$time_s < slice_end,]
    return(pt3_closed_sliced)
  }
  else if(period == 'open'){
    pt3_open <- create_patient_open(filepath)
    qrs_ms_open <- full_dataload$open_chest$QRSmarker_ms
    pt3_open <- na.omit(gen_annotation_index(pt3_open, qrs_ms_open, 'time_ms', 'qrs')) 
    pt3_open <- na.omit(gen_annotation_index(pt3_open, seq(0, nrow(pt3_open)*8, 5000), 'time_ms', 'insp'))
    pt3_open_sliced <- pt3_open[pt3_open$time_s > slice_start & pt3_open$time_s < slice_end,]
    return(pt3_open_sliced)
  }
}
```

```{r Creating closed and open patient dataframes}
pt_closed_sliced <- all_in_one_patient(period = 'closed')
pt_open_sliced <- all_in_one_patient(period = 'open')
```


Gam-modelling

```{r generating GAM object}
# cvp_gam_closed <- bam(
#         cvp ~ s(qrs_rel_index, bs = 'cc', k = 50) +
#             s(insp_rel_index, bs = 'cc', k = 30) +
#             ti(
#                 qrs_rel_index,
#                 insp_rel_index,
#                 bs = c('cc', 'cc'),
#                 k = c(20, 10)
#             ) +
#             s(time_s),
#         method = 'REML',
#         data = pt_closed_sliced,
#         nthreads = 16 # Number of (virtual) cores
#     )
 cvp_gam_open <- bam(
         cvp ~ s(qrs_rel_index, bs = 'cc', k = 50) +
             s(insp_rel_index, bs = 'cc', k = 30) +
             ti(
                 qrs_rel_index,
                 insp_rel_index,
                 bs = c('cc', 'cc'),
                 k = c(20, 10)
             ) +
             s(time_s),
         method = 'REML',
         data = pt_open_sliced,
         nthreads = 16 # Number of (virtual) cores
     )
```


Visualise GAM

```{r visualising gam object, fig.width = 10, fig.height = 7, out.width="100%"}
gratia::draw(cvp_gam_closed)
gratia::draw(cvp_gam_open)
```


Mads' Shiny. Work in  progress.


```{r shiny app}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

patient_list <- paste('pt', str_pad(seq(1,61), 2, pad = "0"), sep = "")

ui <- fluidPage(theme = shinytheme("sandstone"),
  navbarPage("GAM on heart-lung interaction during thoractomy", # Page header
    
    # First page begins
    tabPanel("Main page",
        
        # Parameters
        sidebarPanel(h3("Inputs"),
                     selectInput("patient", label = "Select patient", 
                                 choices = list(patient_list = patient_list),  selected = "pt01"),
                     selectInput("option_chest", label = "Open or closed chest",
                                 choices = list("Open" = "open", "Closed" = "closed"),  selected = "open"),
                     selectInput("method", label = "GAM method",
                                 choices = list("REML" = "REML", "P-REML" = "P-REML", "ML" = "ML",
                                                "P-ML" = "P-ML",  "fREML"="fREML"), selected = "REML"),
                     checkboxInput("somevalue", "Some value", FALSE),
                     sliderInput("qrs_rel_index", label = "Number of basis functions in QRS term",
                                 min = 0, max = 100, value = 50),
                     sliderInput("insp_rel_index", label = "Number of basis functions in inspiration term",
                                 min = 0, max = 100, value = 30),
                     sliderInput("interaction_index1", label = "Number of basis functions for QRS in interaction term",
                                 min = 0, max = 100, value = 20),
                     sliderInput("interaction_index2", label = "Number of basis functions for inspiration in interaction term",
                                 min = 0, max = 100, value = 10),
                     ),
          
        # Main panel for displaying outputs
        mainPanel(plotOutput(outputId = "samlet_plots"), tableOutput("oversigt_tabel"))
    ), 
  
    # Second page begins
    tabPanel("Bins sample plot",
        
        # Parameters
        sidebarPanel(h3("Inputs"), sliderInput("Bins_antal",label = "Number of bins", min = 1, max = 100, value = 50),),
        
        # Main panel for displaying outputs
        mainPanel(plotOutput(outputId = "bin_plot"))
        ),
    
    # Third page begins
    tabPanel("Info", "Created by Andreas, Casper, Mads & Simon"),
    
    
    tabPanel("QRS og INSP",
             mainPanel(plotOutput(outputId = "qrs_plot"), plotOutput(outputId = "insp_plot") ))
  )
)



server <- function(input, output) {
  
   output$samlet_plots <- renderPlot({
     
     cvp_gam <- bam(
         cvp ~ s(qrs_rel_index, bs = 'cc', k = input$qrs_rel_index) +
             s(insp_rel_index, bs = 'cc', k = input$insp_rel_index) +
             ti(qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(input$interaction_index1, input$interaction_index2)) +
             s(time_s),
         method = input$method,
         #rho = 0.95,
         data = pt_data(),
         nthreads = 16 # Number of (virtual) cores
     )
     gratia::draw(cvp_gam)
   })# slutter renderPlot her
  

   
  ## Til tabpanel 2 
   
  output$bin_plot <- renderPlot({
    x <- iris$Sepal.Length
    bins = seq(min(x),max(x), length.out = input$Bins_antal +1)
    hist(x,breaks = bins)
  })
  
  
  ## Til tabpanel 4
  # Til at indlæse rds-filerne
  patient_path_open <- reactive({paste("../GAM_RDS/", input$patient, "OPEN.rds",sep="") })
  pt_data_open <- reactive({ readRDS(patient_path_open(), refhook = NULL) })
  
  patient_path_closed <- reactive({paste("../GAM_RDS/", input$patient, "CLOSED.rds",sep="") })
  pt_data_closed <- reactive({ readRDS(patient_path_closed(), refhook = NULL) })
  
  
  ### prøver qrs:
  output$qrs_plot <- renderPlot({
  ggplot() +
  geom_line(data=gratia::evaluate_smooth(pt_data_open(), 's(qrs_rel_index)'),
            aes(qrs_rel_index,est, colour="open")) +
  geom_line(data=gratia::evaluate_smooth(pt_data_closed(), 's(qrs_rel_index)'),
            aes(qrs_rel_index,est, colour="closed")) +
  scale_color_manual(values = c(
    'open' = 'darkblue',
    'closed' = 'red')) +
  labs(color = 'Status') +
      ggtitle("QRS")
  })
  
  ### prøver insp:
  output$insp_plot <- renderPlot({
  ggplot() +
  geom_line(data=gratia::evaluate_smooth(pt_data_open(), 's(insp_rel_index)'),
            aes(insp_rel_index,est, colour="open")) +
  geom_line(data=gratia::evaluate_smooth(pt_data_closed(), 's(insp_rel_index)'),
            aes(insp_rel_index,est, colour="closed")) +
  scale_color_manual(values = c(
    'open' = 'darkblue',
    'closed' = 'red')) +
  labs(color = 'Status') +
      ggtitle("INSP")
  })
  
  
  
  
}
shinyApp(ui = ui, server = server)
# https://shiny.rstudio.com/articles/layout-guide.html
# https://www.youtube.com/watch?v=PHdIivFAq7Q
```






```{r}
filepath <- "../GAM_RDS/pt09OPEN.rds"
full_dataload <- readRDS(filepath, refhook = NULL)

filepath <- "../GAM_RDS/pt09CLOSED.rds"
full_dataloadclosed <- readRDS(filepath, refhook = NULL)

```

```{r}
gratia::draw(full_dataload)
gratia::draw(full_dataloadclosed)

```

```{r qrs_rel_index}
data_qrs_open <- gratia::evaluate_smooth(full_dataload, 's(qrs_rel_index)')
data_qrs_closed <- gratia::evaluate_smooth(full_dataloadclosed, 's(qrs_rel_index)')
```

```{r insp_rel_index}
data_insp_open <- gratia::evaluate_smooth(full_dataload, 's(insp_rel_index)')
data_insp_closed <- gratia::evaluate_smooth(full_dataloadclosed, 's(insp_rel_index)')
```

```{r time_s}
#data_time_open <- gratia::evaluate_smooth(full_dataload, 's(time_s)')
#data_time_closed <- gratia::evaluate_smooth(full_dataloadclosed, 's(time_s)')
```


```{r individuelle plot}
# ggplot(data = data_qrs_open, aes(qrs_rel_index, est)) +
#   geom_line()
# 
# ggplot(data_insp_open, aes(insp_rel_index, est)) +
#   geom_line()
```


```{r samlet plot qrs}
aa <- ggplot() +
  geom_line(data=data_qrs_open, aes(qrs_rel_index,est, colour="open")) +
  geom_line(data=data_qrs_closed, aes(qrs_rel_index,est, colour="closed")) +
  scale_color_manual(values = c(
    'open' = 'darkblue',
    'closed' = 'red')) +
  labs(color = 'Status')
```



```{r samlet plot insp}
tt <- ggplot() +
  geom_line(data=data_insp_open, aes(insp_rel_index,est, colour="open")) +
  geom_line(data=data_insp_closed, aes(insp_rel_index,est, colour="closed")) +
  scale_color_manual(values = c(
    'open' = 'darkblue',
    'closed' = 'red')) +
  labs(color = 'Status')
```





```{r}
aa + tt
```















```{r}
gratia::draw(full_dataload,       select = 1, rug= FALSE) 
gratia::draw(full_dataloadclosed, select = 1, rug=F)
```

```{r}
gen_predictions <- function(cvp_gam) {
    if (is.null(cvp_gam)) return(NULL)
    
    #find max of insp_index smooth
    insp_index_smooth <- gratia::evaluate_smooth(cvp_gam, 's(insp_index)')
    insp_index_max <- insp_index_smooth$insp_index[which.max(insp_index_smooth$est)]
    
    structured_data <- expand_grid(insp_index = c(
        # Generate predictions for 10 levels of inspiration between start and max inspiration
        seq(0,insp_index_max, length.out = 10), 
        # And 1 prediction 1 sec after max inspiration                                      
        insp_index_max + c(1)),
        # Generate 200 predictions uniformaly across the qrs_rel_index (to get a smooth line)
        qrs_rel_index = seq(0,1, length.out = 200),
        # Choose 'some' position for the trend smooth (or better, do not include it in the prediction)
        time_s = 1)
    
    struct_pred <- predict(cvp_gam, newdata = structured_data, se.fit = TRUE) 
    
    mutate(structured_data, 
           CVP = struct_pred$fit,
           CVP_low = CVP - 1.96 * struct_pred$se.fit,
           CVP_up = CVP + 1.96 * struct_pred$se.fit)
}
```


