---
title: "OpenCloseViz"
author: "Andreas Tind Damgaard"
date: "21/4/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE}
rm(list = ls()) # clearing workspace
library(stringr)
library(ggplot2)
library(dplyr)
library(viridis)
```

```{r select patient and load data}
pt_range <- c(2, 3, 4, 5, 7, 9, 10, 11, 12, 14, 15, 16, 17, 18, 21, 22, 23, 24, 28, 31, 32, 35, 37, 38, 41, 42, 44,45, 46, 47, 48, 51, 52, 53, 54, 55, 57, 58) #seq(1,61) # insert the number of the patient you want to visualize

load_patient <- function(patient_number){
    # a function that loads GAMs in RDS file format using a specific nomenclature
    ptopen <- readRDS(paste0("../GAM_RDS/pt",str_pad(toString(patient_number), 2, pad = "0"), "OPEN.rds"))
    ptclosed <- readRDS(paste0("../GAM_RDS/pt",str_pad(toString(patient_number), 2, pad = "0"), "CLOSED.rds"))
    pt <- list("ptopen" = ptopen, "ptclosed" = ptclosed)
    return(pt)
}


gen_predictions <- function(cvp_gam) {
    # a function that generates predictions according to the given model
    # the code is a slightly modified version of Johannes'
    if (is.null(cvp_gam)) return(NULL)
    
    #find max of insp_index smooth
    insp_rel_index_smooth <- gratia::evaluate_smooth(cvp_gam, 's(insp_rel_index)')
    insp_rel_index_max <- insp_rel_index_smooth$insp_rel_index[which.max(insp_rel_index_smooth$est)]

    structured_data <- expand.grid(insp_rel_index = c(
        # Generate predictions for 10 levels of inspiration between start and max inspiration
        seq(0, 1, length.out = 10)), #insp_rel_index_max, length.out = 10)), 
        # And 1 prediction 1 sec after max inspiration                                      
        #insp_rel_index_max + c(1)), # uncommented for our use case
        # Generate 200 predictions uniformaly across the qrs_rel_index (to get a smooth line)
        qrs_rel_index = seq(0,1, length.out = 500),
        # Choose 'some' position for the trend smooth (or better, do not include it in the prediction)
        time_s = 580)
    
    struct_pred <- predict(cvp_gam, newdata = structured_data, se.fit = TRUE, exclude='s(time_s)') 
    
    mutate(structured_data, 
           CVP = struct_pred$fit,
           CVP_low = CVP - 1.96 * struct_pred$se.fit,
           CVP_up = CVP + 1.96 * struct_pred$se.fit)
}


create_patient_preds <- function(ptopen, ptclosed){
    # a function that creates predictions and combines data from closed and open chest into one data frame 
    pred_open <- gen_predictions(ptopen)
    pred_closed <- gen_predictions(ptclosed)
    pred_both <- cbind(indicator=c(rep("open_chest", nrow(pred_open)),
                                   rep("closed_chest", nrow(pred_closed))),
                       pred_both <- rbind(pred_open, pred_closed))
    return(pred_both)
}


create_viz <- function(pred_both, patient_number){
    # a function that creates a visualization comparing closed and open predictions  
    viz <- ggplot(data = pred_both, aes(x=qrs_rel_index, y=CVP, group = insp_rel_index)) +
    geom_line(aes(color=insp_rel_index), size = 1.1) +
    scale_color_gradientn(colours = turbo(10)) +
    labs(title = paste0("Patient ", patient_number),
         y = "CVP",
         x = "qrs_rel_index") +
    facet_wrap(~ indicator)
    return(viz)
}
```

```{r print plot(s) to pdf}
pdf("closed_and_open_snapshot_viz.pdf", width = 18, height = 5)
for (i in pt_range){
    pt <- load_patient(i)
    preds <- create_patient_preds(ptopen = pt$ptopen, ptclosed = pt$ptclosed)
    viz <- create_viz(pred_both = preds, patient_number = i)
    print(viz)
}
dev.off()
```


