---
title: "GAM for thoracotomy waveforms"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE}
rm(list = ls()) # clearing workspace
library(viridis)
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
library(shiny)
library(shinythemes)
library(shinyTime)
library(data.table)
library(readr)
library(dygraphs)
library(dplyr)
library(gridExtra)
#library(shinyBS)
```

Functions:

```{r}
#pt_range <- c(2, 3, 4) #seq(1,61) # insert the number of the patient you want to visualize

# load_patient <- function(patient_number){
#     # a function that loads GAMs in RDS file format using a specific nomenclature
#     ptopen <- readRDS(paste0("../GAM_RDS/",patient_number, "OPEN.rds"))
#     ptclosed <- readRDS(paste0("../GAM_RDS/",patient_number, "CLOSED.rds"))
#     pt <- list("ptopen" = ptopen, "ptclosed" = ptclosed)
#     return(pt)
# }


gen_predictions <- function(cvp_gam) {
    # a function that generates predictions according to the given model
    # the code is a slightly modified version of Johannes'
    if (is.null(cvp_gam)) return(NULL)
    
    #find max of insp_index smooth
    #insp_rel_index_smooth <- gratia::evaluate_smooth(cvp_gam, 's(insp_rel_index)')
    #insp_rel_index_max <- insp_rel_index_smooth$insp_rel_index[which.max(insp_rel_index_smooth$est)]

    structured_data <- expand.grid(insp_rel_index = c(
        # Generate predictions for 10 levels of inspiration between start and max inspiration
        seq(0, 0.9, length.out = 10)), #insp_rel_index_max, length.out = 10)), 
        # And 1 prediction 1 sec after max inspiration                                      
        #insp_rel_index_max + c(1)), # uncommented for our use case
        # Generate 200 predictions uniformaly across the qrs_rel_index (to get a smooth line)
        qrs_rel_index = seq(0,1, length.out = 500),
        # Choose 'some' position for the trend smooth (or better, do not include it in the prediction)
        time_s = 580)
    
    struct_pred <- predict(cvp_gam, newdata = structured_data, se.fit = TRUE, exclude='s(time_s)') 
    
    mutate(structured_data, 
           CVP = struct_pred$fit,
           CVP_low = CVP - 1.96 * struct_pred$se.fit,
           CVP_up = CVP + 1.96 * struct_pred$se.fit)
}


create_patient_preds <- function(ptopen, ptclosed){
    # a function that creates predictions and combines data from closed and open chest into one data frame 
    pred_open <- gen_predictions(ptopen)
    pred_closed <- gen_predictions(ptclosed)
    pred_both <- cbind(indicator=c(rep("open_chest", nrow(pred_open)),
                                   rep("closed_chest", nrow(pred_closed))),
                       pred_both <- rbind(pred_open, pred_closed)) # makes an indicator variable wether it is open or closed chest
    return(pred_both)
}



stacked_plot <- function(io, ic, qo, qc, patient_number = NULL){
  # This function takes (inspiration/qrs) and (open/closed-chest) and outputs the plot for each combination.

  colnames(io)[3] <- "rel_index"
  colnames(ic)[3] <- "rel_index"
  colnames(qo)[3] <- "rel_index"
  colnames(qc)[3] <- "rel_index"
  
  comb <- cbind(indicator=c(rep("open_chest", nrow(io)),
                            rep("closed_chest", nrow(ic))),
                both <- rbind(io, ic, qo, qc)) # combines the data to make it easier to work with

  #creates the plots with ggplot
  viz <- ggplot(data=comb, aes(x=rel_index, y=est, group=indicator)) +
    geom_line(aes(color=indicator), size = 0.9) +
    facet_wrap(~ smooth) +
    labs(title = "The marginal effects of respiration and QRS, respectively, on CVP",
         y="Estimated effect on CVP",
         x="Relative respiration/QRS index",
         color = "Time period") +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)))
  return(viz)
}



stacked_diff_plot <- function(io, ic, qo, qc){
  # This function takes (inspiration/qrs) and (open/closed-chest) and plots the difference in open/closed-chest.

  colnames(io)[3] <- "rel_index"
  colnames(ic)[3] <- "rel_index"
  colnames(qo)[3] <- "rel_index"
  colnames(qc)[3] <- "rel_index"
  
  combo <- rbind(io, qo)
  combo <- combo[order(combo$smooth,combo$rel_index),] # sorts the data
  combc <- rbind(ic, qc)
  combc <- combc[order(combc$smooth,combc$rel_index),]
  
  combo$est_diff <- combo$est - combc$est # takes the difference

  # plots
  viz <- ggplot(data=combo, aes(x=rel_index, y=est_diff)) +
    geom_line(aes(), size = 0.9) +
    facet_wrap(~ smooth) +
    labs(title = "The difference in marginal effects (respiration and QRS) before and after thoractomy",
         y="Effect during open chest minus effect during closed chest",
         x="Relative respiration/QRS index") +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)))
  return(viz)
}


create_contour_patient <- function(odata, cdata){
  # this function takes open- and closed data. It is a helper function that combines the two datasets in one table 
  # with an added column indicating whether the chest is open or closed
  
  gather_in_one <- rbind(odata, cdata)
  gather_in_one$indicator <- cbind(c(rep("open_chest", nrow(odata)),
                                     rep("closed_chest", nrow(cdata))))
  return(gather_in_one)
}



move_contour <- function(data_contour, input_scale_open, input_scale_closed){
  # this function takes the combined dataset for open and closed and outputs a new dataset where the order has been rearranged
  data_contour <- mutate(data_contour,
                         est = c(est[((100 - input_scale_open) * 100 + 1):10000],
                                 est[1:((100 - input_scale_open) * 100)],
                                 est[((100 - input_scale_closed) * 100 + 10001):20000],
                                 est[10001:((100 - input_scale_closed) * 100 + 10000)]))
  return(data_contour)
}


create_contour_diff_data <- function(data_set){
  # this function takes the combined dataset and outputs the difference in open and closed chest.
  # this is done by subtracting the the open estimate from the closed estimate.
  data_set <- data_set[order(data_set$indicator, data_set$qrs_rel_index, data_set$insp_rel_index),]
  new_diff_data <- data.frame(qrs_rel_index = data_set$qrs_rel_index[1:10000],
                              insp_rel_index = data_set$insp_rel_index[1:10000],
                              est = data_set$est[10001:20000] - data_set$est[1:10000], # open minus closed est
                              indicator = rep("Difference", 10000))
  return(new_diff_data)
}


create_contour_viz <- function(data_set,
                               lab.title = "Effect of interaction term between respiration and QRS on CVP",
                               lab.y = "Relative respiration index",
                               lab.x = "Relative QRS index",
                               lab.legend = "Estimated effect\non CVP",
                               wrap = TRUE,
                               left_margin = 5){
  
  # This functions plots a contour plot for a dataset with x-axis as QRS and y as repiration index
  viz <- ggplot(data_set, aes(qrs_rel_index, insp_rel_index, z = est)) + # x,y and z dimensions
    geom_raster(aes(fill = est)) + # this creates the contour-plot
    geom_contour(colour = "black") +
    scale_fill_gradientn(colours=c("#0000FFFF","#FFFFFFFF","#FF0000FF")) +
      labs(title = lab.title,
           y = lab.y,
           x = lab.x,
           fill = lab.legend) +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = left_margin, b = 0, l = 0)))
  if(wrap){
    viz <- viz + facet_wrap(~ indicator)}
  return(viz)
}


create_viz <- function(pred_both, patient_number = NULL){
    # a function that creates a visualization comparing closed and open predictions with 10 lines
  
    viz <- ggplot(data = pred_both, aes(x=qrs_rel_index, y=CVP, group = insp_rel_index)) + 
      # takes x and y values. Where it groups over 10 different insp_rel_index indekses 
      geom_line(aes(color=insp_rel_index), size = 0.9) +
      scale_color_gradientn(colours = turbo(10)) +
      labs(title = "Change in CVP as a function of relative QRS index at selected relative respiration index times",
           y = "CVP",
           x = "Relative QRS index",
           colour = "Relative        \nrespiration index") +
      facet_wrap(~ indicator) +
      theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)))
    return(viz)
}



diff_snap_plot <- function(preds_data, lab.legend = "Relative        \nrespiration index"){
  # this function takes the combined shifted data, sorts it, takes the difference in open and closed where it plots this difference for 10 different lines of indeks' 
  
  preds_data <- preds_data[order(preds_data$indicator, preds_data$insp_rel_index, preds_data$qrs_rel_index),]
  closed_and <- preds_data[1:5000,]
  open_and <- preds_data[5001:10000,]
  
  data_to_plot <- tibble(insp_rel_index = (closed_and$insp_rel_index + open_and$insp_rel_index)/2,
                         qrs_rel_index = closed_and$qrs_rel_index,
                         CVP = open_and$CVP - closed_and$CVP, # takes the difference in cvp
                         indicator = rep("Difference", 5000))

  # plots the difference
  viz <- ggplot(data = data_to_plot, aes(x=qrs_rel_index, y=CVP, group = insp_rel_index)) +
    geom_line(aes(color=insp_rel_index), size = 0.9) +
    scale_color_gradientn(colours = turbo(10)) +
    labs(title = "The difference in CVP as a function of relative QRS index at selected relative respiration index times",
         y = "Difference in CVP (open minus close)",
         x = "Relative QRS index",
         colour = lab.legend) +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0))) + 
    facet_wrap(~ indicator)
  return(viz)
}

insp_shift_data <- function(data_set, shift_value_open, shift_value_closed){
  # This function also shifts data. This is done for the datasets containing 10 different lines
  data_set <- mutate(data_set, insp_rel_index = ifelse(indicator=="open_chest",
                                                       (data_set$insp_rel_index + shift_value_open) %% 1,
                                                       (data_set$insp_rel_index + shift_value_closed) %% 1))
  return(data_set)
}


give_it_center <- function(data_set, center = 50){
  # this function takes a dataset and calculates whether the data should be shifted 
  # to the left or right so the largest value is the middel index
  if (which.max(data_set$est) > center ){ # this is executed if the largest input is to the right of the center
    biggest <- which.max(data_set$est)
    value_to_subtract <- data_set$insp_rel_index[biggest] - data_set$insp_rel_index[center]
    data_set$insp_rel_index <- data_set$insp_rel_index - value_to_subtract
    for (index in 1:length(data_set$insp_rel_index)) {
      if (data_set$insp_rel_index[index] < 0 ){
        data_set$insp_rel_index[index] <- data_set$insp_rel_index[index] +1
      }
    }
  } else{ # this is executed if the largest input is to the left (or exactly on) the center
    smallest <- which.max(data_set$est)
    value_to_add <- data_set$insp_rel_index[center] - data_set$insp_rel_index[smallest]
    data_set$insp_rel_index <- data_set$insp_rel_index + value_to_add
    for (index in 1:length(data_set$insp_rel_index)) {
      if (data_set$insp_rel_index[index] > 1 ){
        data_set$insp_rel_index[index] <- data_set$insp_rel_index[index] -1
      }
    }
  }
  return(data_set)
}


insp_add_sub_val <- function(data_set, center = 50){
  # takes dataset and outputs value to add/subtract from index of a dataset depending on given center value. 
  if (which.max(data_set$est) > center ){
    biggest <- which.max(data_set$est)
    value_to_subtract <- data_set$insp_rel_index[center] - data_set$insp_rel_index[biggest]
    return(value_to_subtract)
  }else{
    smallest <- which.max(data_set$est)
    value_to_add <- data_set$insp_rel_index[center] - data_set$insp_rel_index[smallest]
    return(value_to_add)
  }
}




create_dygraphs <- function(obj, closed, ptnumber){
  # this is a helper function that styles the residual plots
  if (closed==TRUE){
    res1 <- dygraph_gam(obj, resid=TRUE)
    res1$x$group <- NULL
    res1$x$attrs$ylabel <- "CVP"
    res1$x$attrs$title <- paste0(ptnumber, " - Closed chest")
    res1$x$attrs$xlabel <- "Time"
  }
  else{
    res1 <- dygraph_gam(obj, resid=TRUE)
    res1$x$attrs$ylabel <- "CVP"
    res1$x$attrs$title <- paste0(ptnumber, " - Open chest")
    res1$x$attrs$xlabel <- "Time"
  }
  return(res1)
}

```

Testing area:

```{r}
# testpt <- "pt02"
# center_open <- 50
# center_closed <- 58
# 
# patient_path_open <- paste("../GAM_RDS/", testpt, "OPEN.rds",sep="")
# pt_data_open <- readRDS(patient_path_open, refhook = NULL)
# 
# patient_path_closed <- paste("../GAM_RDS/", testpt, "CLOSED.rds",sep="")
# pt_data_closed <- readRDS(patient_path_closed, refhook = NULL)
# 
# #testio <- give_it_center(gratia::evaluate_smooth(pt_data_open,'s(insp_rel_index)'),50)
# #testic <- give_it_center(gratia::evaluate_smooth(pt_data_closed,'s(insp_rel_index)'),58)
# #testqo <- gratia::evaluate_smooth(pt_data_open,'s(qrs_rel_index)')
# #testqc <- gratia::evaluate_smooth(pt_data_closed,'s(qrs_rel_index)')
# 
# 
# testo <- gratia::evaluate_smooth(pt_data_open, 'ti(qrs_rel_index,insp_rel_index)')
# testc <- gratia::evaluate_smooth(pt_data_closed, 'ti(qrs_rel_index,insp_rel_index)')
# 
# 
# test <- move_contour(create_contour_patient(testo, testc),
#                                             center_open,
#                                             center_closed)
# test <- test[order(test$indicator, test$qrs_rel_index, test$insp_rel_index),]
# test1 <- data.frame(qrs_rel_index = test$qrs_rel_index[1:10000],
#                     insp_rel_index = test$insp_rel_index[1:10000],
#                     est = test$est[10001:20000] - test$est[1:10000],
#                     indicator = rep("Difference", 10000)) # open minus closed est
# test$indicator <- as.character(test$indicator)
# test3 <- bind_rows(test[,c(3,4,5,7)],test1)
# 
# merge_contour_data_diff <- function(data_set){
#   data_set <- data_set[order(data_set$indicator, data_set$qrs_rel_index, data_set$insp_rel_index),]
#   data_set_diff <- data.frame(qrs_rel_index = test$qrs_rel_index[1:10000],
#                               insp_rel_index = test$insp_rel_index[1:10000],
#                               est = test$est[10001:20000] - test$est[1:10000],
#                               indicator = rep("Difference", 10000)) # open minus closed est
#   data_set$indicator <- as.character(data_set$indicator)
#   final <- bind_rows(data_set[,c(3,4,5,7),], data_set_diff)
#   final <- transform(final, indicator=factor(indicator, levels = c("closed_chest","open_chest","Difference")))
#   return(final)
# }
# 
# create_contour_viz(merge_contour_data_diff(test))


```



Shiny below:

```{r shiny app}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
table_values <- read_csv("../GAM_RDS/CV_MAE.csv") 
bic_values <- read_csv("../GAM_RDS/CV_BIC.csv") 
mae_values <- read_csv("../GAM_RDS/CV_MAE_BIC.csv") 

patient_list <- paste('pt', str_pad(c(2, 3, 4, 5, 7, 9, 10, 11, 12, 14, 15, 16, 17, 18, 21, 22, 23, 24, 28, 31, 32, 
                                      35, 37, 38, 41, 42, 44, 45, 46, 47, 48, 51, 52, 53, 54, 55, 57, 58), 
                                    2, pad = "0"), sep = "")

ui <- fluidPage(
  tags$head(
    tags$script(
      HTML("
            $(document).ready(function(){
              // Mark columns we want to toggle
              $('body').find('div [class=col-sm-4]').addClass('sidebarPanel');
              $('body').find('div [class=col-sm-8]').addClass('mainPanel');
            })


            Shiny.addCustomMessageHandler ('resize',function (message) {
              $('.sidebarPanel').toggle();
              $('.mainPanel').toggleClass('col-sm-8 col-sm-12');
              $(window).trigger('resize')
            });

           "))
  ),
  actionButton("showpanel", "Show/hide sidebar"),
  theme = shinytheme("sandstone"),
  navbarPage("GAM on heart-lung interaction during thoractomy", # Page header

    # First page begins
    tabPanel("Main page",
     sidebarLayout(

        # Parameters
        sidebarPanel(selectInput("patient", label = "Select patient",
                                 choices = list(patient_list = patient_list),  selected = "pt02"),
                     sliderInput("center_closed", label = "Index placement of largest respiration effect during closed chest",
                                 min = 1, max = 99, value = 50),
                     sliderInput("center_open", label = "Index placement of largest respiration effect during open chest",
                                 min = 1, max = 99, value = 50),
                     tags$div(class="multicol", checkboxGroupInput("showhide", "Plots to show",
                                        choices = c("Regular plots" = "reg", "Closed/open difference plots" = "diff"),
                                        selected = c("reg"))),
                     h3("Model details"),
                     tableOutput('table'),
                     tags$style(type="text/css", "#table tr:first-child, td:first-child { font-weight: bold;}"),
                     tags$style(type="text/css",
                                "#table tr:nth-child(1), tr:nth-child(5), tr:nth-child(10) {border-bottom: solid 2px black;}"),
                     tags$style(type="text/css", "#table tr:hover {background-color: #f8fff5;"),
                     htmlOutput("modeltext")),

        # Main panel for displaying outputs
        mainPanel(plotOutput(outputId = "all_plots", height = "1200px", width = "100%")))
    ), 
    
    # Second page begins
    tabPanel("Residuals",
             sidebarPanel(h3("Description"), htmlOutput("text2")),
             mainPanel(dygraphOutput("dygraph1"), dygraphOutput("dygraph2"))
             ),
  
    # Third page begins
    tabPanel("Info", "Created by Andreas, Casper, Mads & Simon")
  )
)

server <- function(input, output, session) {
  
  # Show/hide sidepanel
  observeEvent(input$showpanel,{
    session$sendCustomMessage(type = 'resize', message = 1)
  })
  
    
  # Loading data
  patient_path_open <- reactive({paste("../GAM_RDS/", input$patient, "OPEN.rds",sep="") })
  pt_data_open <- reactive({readRDS(patient_path_open(), refhook = NULL) })
  
  patient_path_closed <- reactive({paste("../GAM_RDS/", input$patient, "CLOSED.rds",sep="") })
  pt_data_closed <- reactive({readRDS(patient_path_closed(), refhook = NULL) })

  open_add_sub_value <- reactive({insp_add_sub_val(gratia::evaluate_smooth(pt_data_open(),'s(insp_rel_index)'),
                                                   input$center_open)})
  closed_add_sub_value <- reactive({insp_add_sub_val(gratia::evaluate_smooth(pt_data_closed(),'s(insp_rel_index)'), 
                                                     input$center_closed)})
  
  # For snap plots
  preds <- reactive({insp_shift_data(create_patient_preds(pt_data_open(), pt_data_closed()),
                                     open_add_sub_value(), 
                                     closed_add_sub_value())})
  snapplot <- reactive({create_viz(pred_both = preds())})
  
  # For snap diff plots
  snapplot_diff <- reactive({diff_snap_plot(preds(), lab.legend = "Relative \nrespiration index                   ")})

  # For stacked plots
  stackedp <- reactive({stacked_plot(
    give_it_center(gratia::evaluate_smooth(pt_data_open(),'s(insp_rel_index)'),input$center_open),
    give_it_center(gratia::evaluate_smooth(pt_data_closed(),'s(insp_rel_index)'),input$center_closed),
    gratia::evaluate_smooth(pt_data_open(),'s(qrs_rel_index)'),
    gratia::evaluate_smooth(pt_data_closed(),'s(qrs_rel_index)'))})
  
  # For stacked diff plots
  stackeddiffp <- reactive({stacked_diff_plot(
    give_it_center(gratia::evaluate_smooth(pt_data_open(),'s(insp_rel_index)'),input$center_open),
    give_it_center(gratia::evaluate_smooth(pt_data_closed(),'s(insp_rel_index)'),input$center_closed),
    gratia::evaluate_smooth(pt_data_open(),'s(qrs_rel_index)'),
    gratia::evaluate_smooth(pt_data_closed(),'s(qrs_rel_index)'))})
  
  
  # For contour plots
  data_open_contour <- reactive({gratia::evaluate_smooth(pt_data_open(), 'ti(qrs_rel_index,insp_rel_index)')})
  data_closed_contour <- reactive({gratia::evaluate_smooth(pt_data_closed(), 'ti(qrs_rel_index,insp_rel_index)')})
  
  contourp <- reactive({create_contour_viz(move_contour(create_contour_patient(data_open_contour(), 
                                                                               data_closed_contour()),
                                                        input$center_open,
                                                        input$center_closed))})
  # For contour difference plots
  contourdiffp <- reactive({create_contour_viz(create_contour_diff_data(move_contour(create_contour_patient(
            data_open_contour(),
            data_closed_contour()),
        input$center_open,
        input$center_closed)),
    lab.legend = "Interaction effect during   \nopen chest minus interaction \neffect during closed chest",
    lab.title = "The difference in interaction effect (respiration and QRS) before and after thoractomy",
    wrap = TRUE,
    left_margin = 12)})
  
  
  
  # Rendering plots
  output$all_plots <- renderPlot({

    if (length(input$showhide) == 0) {
      ggplot(data.frame())
    } else {
      if (length(input$showhide) == 2){
        plotlist <- list(stackedp(), contourp(), snapplot(), stackeddiffp(), contourdiffp(), snapplot_diff())
        plotmatrix <- rbind(c(1,1,1,1,1,4,4,4,4,4),
                            c(2,2,2,2,2,5,5,5,5,5),
                            c(3,3,3,3,3,6,6,6,6,6))
      } else {
        if ("reg" == input$showhide){
          plotlist <- list(stackedp(), contourp(), snapplot())
          plotmatrix <- rbind(c(1),
                              c(2),
                              c(3))
        }
        if ("diff" == input$showhide){
          plotlist <- list(stackeddiffp(), contourdiffp(), snapplot_diff())
          plotmatrix <- rbind(c(4),
                              c(5),
                              c(6))
        }
      }
      grid.arrange(grobs = plotlist, layout_matrix = plotmatrix, nrow = 3)
    }
  }) # renderPlot ends here
  
  # Dygraphs
  dy_graph1 <- reactive({create_dygraphs(pt_data_closed(), closed=TRUE, input$patient)})
  dy_graph2 <- reactive({create_dygraphs(pt_data_open(), closed=FALSE, input$patient)})
  
  output$dygraph1 <- renderDygraph({dy_graph1()})
  output$dygraph2 <- renderDygraph({dy_graph2()})
  
  # Dygraph render ends here
  
  output$text2 <- renderText({
    HTML('On this page you can see the observed values, the predicted values of the models, and the residuals.
         <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
         <br><br><br><br><br><br><br>')
    }) # Render Text for second page
  
  # This is a TABLE!
  data_time_open  <- reactive({gratia::evaluate_smooth(pt_data_open(), 's(time_s)')})
  data_time_closed <- reactive({gratia::evaluate_smooth(pt_data_closed(), 's(time_s)')})
  
  
  model_table <- reactive({rename(subset(table_values,
                                         Model %in% c(paste0(input$patient, "OPEN.rds"),
                                                      paste0(input$patient, "CLOSED.rds")),
                                         select = c("Model")),
                                  `Model file` = Model)})
  
  cv_mae_table <- reactive({round(rename(subset(table_values,
                                                Model %in% c(paste0(input$patient, "OPEN.rds"),
                                                             paste0(input$patient, "CLOSED.rds")),
                                                select = c("CV_MAE")),
                                         `Cross validation MAE` = CV_MAE),
                                  3)})
  
  mae_table <- reactive({round(rename(subset(mae_values,
                                             Model %in% c(paste0(input$patient, "OPEN.rds"),
                                                          paste0(input$patient, "CLOSED.rds")),
                                             select = c("Actual Model MAE")),
                                      `Model MAE` = `Actual Model MAE`),
                               3)})
  
  mae_table2 <- reactive({round(subset(mae_values,
                                       Model %in% c(paste0(input$patient, "OPEN.rds"),
                                                    paste0(input$patient, "CLOSED.rds")),
                                       select = c("LM MAE","Poly1 MAE","Poly2 MAE")),
                                3)})
  
  bic_table <- reactive({round(rename(subset(bic_values,
                                             Model %in% c(paste0(input$patient, "OPEN.rds"),
                                                          paste0(input$patient, "CLOSED.rds")),
                                             select = c("Actual Model BIC","LM BIC","Poly1 BIC","Poly2 BIC")),
                                      `Model BIC`=`Actual Model BIC`))})
  
  
  intercept <- reactive({round(c(pt_data_open()[["coefficients"]][1],
                                 pt_data_closed()[["coefficients"]][1]),3)})
  
  start_time <- reactive({formatC(round(c(min(data_time_closed()$time_s), min(data_time_open()$time_s)), 1), 1, format="f")})
  end_time <- reactive({formatC(round(c(max(data_time_closed()$time_s), max(data_time_open()$time_s)), 1), 1, format="f")})
  diff_time <- reactive({formatC(round(c(max(data_time_closed()$time_s) - min(data_time_closed()$time_s),
                                         max(data_time_open()$time_s) - min(data_time_open()$time_s)), 1), 1, format="f")})
  
  output$table <- renderTable({t(cbind(model_table(),
                                       `Model intercept` = intercept(),
                                       `Model data start time` = start_time(),
                                       `Model data end time` = end_time(),
                                       `Model data time length` = diff_time(),
                                       mae_table(),
                                       cv_mae_table(),
                                       mae_table2(),
                                       bic_table()))}, 
                              rownames=TRUE, 
                              colnames=FALSE)
  
  output$modeltext <- renderUI({
                str1 <- "LM: Linear Regression Model"
                str11 <- "CVP = &beta;<sub>0</sub> (qrs_rel_index &times; insp_rel_index) + &beta;<sub>1</sub> qrs_rel_index + 
                  &beta;<sub>2</sub> insp_rel_index + &beta;<sub>3</sub> time + &epsilon;."
                str111 <- ""
                str2 <- "Poly1: Polynomial Regression Model 1"
                str22 <- "CVP = &beta;<sub>0</sub> qrs_rel_index<sup>12</sup> + &beta;<sub>1</sub> insp_rel_index<sup>8</sup> + 
                  &beta;<sub>2</sub> time<sup>3</sup> + &epsilon;."
                str222 <- ""
                str3 <- "Poly 2: Polynomial Regression Model 2"
                str33 <- "CVP = &beta;<sub>0</sub> qrs_rel_index<sup>23</sup> + &beta;<sub>1</sub> insp_rel_index<sup>23</sup> + 
                  &beta;<sub>2</sub> time<sup>23</sup> + &epsilon;."
                str333 <- ""
                HTML(paste(str1, str11, str111, str2, str22, str222, str3, str33, str333, sep = '<br/>') )
            })   
  
} # server ends

OurApp <- shinyApp(ui = ui, server = server)
runApp(OurApp)
```

