---
title: "GAM for thoracotomy waveforms"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE}
rm(list = ls()) # clearing workspace
library(waveformtools)
library(tidyverse)
library(mgcv)
library(hms)
library(shiny)
library(shinythemes)
library(shinyTime)
library(data.table)
library(readr)
library(dygraphs)
library(dplyr)
```


```{r loading data}
filepath <- "../Datasets/thoracotomy_waveforms_prelim/pt03.RDS"
full_dataload <- readRDS(filepath, refhook = NULL)
```


```{r creating functions}
add_time <- function(data, ms_between_obs = 8, time_origin = "2021-09-03") {
  #' adds a column containing time with increments of ms_between_obs
  #' data:             a dataframe like structure
  #' ms_between_obs:   the amount of milliseconds between each cycle
  df <- tibble(data)
  df$time_ms <- seq(0, nrow(df)*ms_between_obs-ms_between_obs, ms_between_obs)
  df$time_s <- df$time_ms / 1000
  return(df)
}

create_patient <- function(filepath) {
  #' creates a dataframe containing cvp and time in ms and s for open chest
  #' filepath:        the path of the patient file
  dataload <- readRDS(filepath, refhook = NULL)
  patient <- data.frame(open_chest_cvp = dataload$open_chest$CVP) # extract cvp numbers from data
  patient <- add_time(patient)
  return(patient)
}
```


There are 125 measurements of CVP each second -> 1/125s = 0.008/s. 
This means that there are 0.008 seconds between each measurement. 
To get ms we simply multiply by 1.000.



```{r initializing patient}
pt3 <- create_patient(filepath)
qrs_ms <- full_dataload$open_chest$QRSmarker_ms

# The following code is to give an index to each measurement for which position it has in its heartbeat 
# cycle. Also removes rows containing NAs giving only rows where we know start and end of cycle
pt3 <- na.omit(gen_annotation_index(pt3, qrs_ms, 'time_ms', 'qrs')) 
pt3 <- na.omit(gen_annotation_index(pt3, seq(0, nrow(pt3)*8, 5000), 'time_ms', 'insp'))
```


Inspect data:

```{r inspecting cvp over time}
dygraph(data = pt3[,c("time_s","open_chest_cvp")])
```


We now slice after finding appropriate time slot in the above inspection. 
Below the periode between 130s and 190s has been selected.

```{r slicing data}
pt3_sliced <- pt3[pt3$time_s > 130 & pt3$time_s < 190,]
```


Gam-modelling

```{r generating GAM object}
cvp_gam <- bam(
        open_chest_cvp ~ s(qrs_rel_index, bs = 'cc', k = 50) +
            s(insp_rel_indx, bs = 'cc', k = 30) +
            ti(
                qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(20, 10)
            ) +
            s(time_s),
        method = 'REML',
        data = pt3_sliced,
        nthreads = 16 # Number of (virtual) cores
    )
```


Visualise GAM

```{r visualising gam object, fig.width = 10, fig.height = 7, out.width="100%"}
gratia::draw(cvp_gam)
```


Mads' Shiny. Work in progress.

```{r shiny app}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)


ui <- fluidPage(theme = shinytheme("cerulean"),
  navbarPage("Shiny stuff",
             
  # Page header
  tabPanel("Justering af parametre",
  # Input values
  sidebarPanel(
    h3("Inputs"),
    sliderInput("qrs_rel_index", label = "qrs_rel_index - k",
                min = 0, max = 100,
                value = 50),
    sliderInput("insp_rel_index", label = "insp_rel_index - k",
                min = 0, max = 100,
                value = 30),
    selectInput("method", label = "Method:", 
                choices = list("REML" = "REML", "P-REML" = "P-REML", "ML" = "ML", 
                               "P-ML" = "P-ML",  "fREML"="fREML"), 
                selected = "REML"),
    sliderInput("interaction_index1", label = "interaction_index1 - k",
                min = 0, max = 100,
                value = 20),
    sliderInput("interaction_index2", label = "interaction_index2 - k",
                min = 0, max = 100,
                value = 10),
  
  # Set to custom time 
  #timeInput("time_start", "Start", value = strptime("18:42:00", "%T")),
  
  #timeInput("time_slut", "Slut", value = strptime("18:43:00", "%T")),
  
  ),
      # Main panel for displaying outputs ----
    mainPanel(
      # Output: plots ----
      plotOutput(outputId = "samlet_plots"),
      tableOutput("oversigt_tabel")
    )
  ),#tabpanel 1 slut
  
  tabPanel("Blomster og Bins bby", 
           sidebarPanel(
                h3("Blomster"),
    sliderInput("Bins_antal", label = "Bins baby",
                min = 1, max = 100,
                value = 50),
           ),
    mainPanel(
      # Output: plots ----
      plotOutput(outputId = "bin_plot")
      )
    ),
  
  tabPanel("Info", "Lavet af en sej studiegruppe")

  )#navbarpage 
)

server <- function(input, output) {
  
  output$samlet_plots <- renderPlot({
    
    cvp_gam <- bam(
        open_chest_cvp ~ s(qrs_rel_index, bs = 'cc', k = input$qrs_rel_index) +
            s(insp_rel_index, bs = 'cc', k = input$insp_rel_index) +
            ti(
                qrs_rel_index,
                insp_rel_index,
                bs = c('cc', 'cc'),
                k = c(input$interaction_index1, input$interaction_index2)
            ) +
            s(time_s),
        method = input$method,
        #rho = 0.95,
        data = pt3_sliced,
        nthreads = 16 # Number of (virtual) cores
    )
    gratia::draw(cvp_gam)
  })# slutter renderPlot her
  
  output$oversigt_tabel <- renderTable({data.frame(name =c("Residualer i anden", "REML_score"), value=c(sum(cvp_gam$residuals^2), unname(cvp_gam$gcv.ubre[1])))
    })

  
  output$bin_plot <- renderPlot({
    x <- iris$Sepal.Length
    bins = seq(min(x),max(x), length.out = input$Bins_antal +1)
    hist(x,breaks = bins)
  })
  
}
shinyApp(ui = ui, server = server)
# https://shiny.rstudio.com/articles/layout-guide.html
# https://www.youtube.com/watch?v=PHdIivFAq7Q
```

